spring:
  application:
    name: uwb-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: uwb-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/uwb/**
          filters:
            - AuthenticationFilter
        - id: uwb-notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/uwb-notification/**
          filters:
            - AuthenticationFilter
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

server:
  port: 8080

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351