spring:
  application:
    name: uwb-notification-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      bootstrap-servers: ${KAFKA_URL}
      group-id: uwb
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351