spring:
  application:
    name: uwb-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    scheduling:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      bootstrap-servers: ${KAFKA_URL}
      group-id: uwb
      auto-offset-reset: earliest
  jackson.serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

tpd:
  topic-name: advice-topic
  messages-per-request: 10

server:
  port: 8081

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

application:
  backgroundPath: D:\Users\michr\source\repos\UWB_DETAILS\
  objectIconPath: D:\Users\michr\source\repos\UWB_DETAILS\object_icons\